#!/usr/bin/env python3
"""
A simple script to count the number of samples in the training and testing JSON files
generated by the LC-LLM data converter.
"""

import json


def count_samples_in_file(file_path: str):
    """
    Opens a JSON file, counts the number of samples, and prints the result.

    Args:
        file_path (str): The path to the JSON file.
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            # Load the entire JSON file into a Python list
            data = json.load(f)

            # The number of samples is the length of the list
            sample_count = len(data)

            print(f"✅ Success: Found {sample_count} samples in '{file_path}'.")

    except FileNotFoundError:
        print(f"❌ Error: The file '{file_path}' was not found. Please ensure the file exists in the same directory.")
    except json.JSONDecodeError:
        print(f"❌ Error: The file '{file_path}' is not a valid JSON file. It might be corrupted or empty.")
    except TypeError:
        print(f"❌ Error: The data in '{file_path}' is not a list. The script expects a JSON array (a list of samples).")
    except Exception as e:
        print(f"An unexpected error occurred while processing '{file_path}': {e}")


if __name__ == "__main__":
    # --- Configuration ---
    # These should match the output filenames from your data preparation script
    TRAINING_FILE = "sam_training_data_with_deltavx.json"
    TESTING_FILE = "sam_testing_data_with_deltavx.json"

    print("--- Counting Samples ---")
    count_samples_in_file(TRAINING_FILE)
    count_samples_in_file(TESTING_FILE)
    print("------------------------")